### ISSUE TITLE
Array 0.4

### ISSUE THREAD

**Issue by iainlane** [sebfisch/haskell-regexp#21]
Hi,

GHC 7.4.1 ships with array 0.4. weighted-regexp's cabal file specifies a constraint that excludes this. It seems that this constraint can just be relaxed and the package will build just fine. Please consider making this change.

Thanks :-)

**Comment by sebfisch** [comment]
Tested and pushed: 49ddcfffdfb1782fbaaf2f5efc8342765a5d386a
